### ISSUE TITLE
Slider Height CSS Issue

### ISSUE THREAD

**Issue by BarryAbrams** [Surface51/accessible_slider#2]
![screen-shot-2015-09-16-at-5 05 34-pm](https://cloud.githubusercontent.com/assets/6731089/9919917/84f62f0e-5c95-11e5-8fb9-3d9e511c0417.jpg)

There's something going on with the slider height css styles.

**Comment by michelledarling** [comment]
Seriously, Josh?  Why isn't this fixed yet??

:D

On Wed, Sep 16, 2015 at 5:14 PM, BarryAbrams notifications@github.com
wrote:

> Reopened #2 https://github.com/Surface51/accessible_slider/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Surface51/accessible_slider/issues/2#event-411528325.

## 

_michelle darling | web developer_
.............................

_S U R F A C E  5 1_

804 n neil street/square 1
champaign il 61820
p 217 356 1300

**Comment by BarryAbrams** [comment]
Josh: We were experimenting with github's issue tracker. Don't take it personally.

**Comment by joshmiethe** [comment]
fixed css and added slide transition options
latest commit be0d5459e6
