### ISSUE TITLE
Focus state on indicator needs styles

### ISSUE THREAD

**Issue by BarryAbrams** [Surface51/accessible_slider#4]
![screen shot 2015-09-17 at 12 07 24 pm](https://cloud.githubusercontent.com/assets/6731089/9940363/13c39b5a-5d35-11e5-89cd-300adbf97854.png)

Now that the accessible stuff is working, the indicators are focusable. It just needs some clean up like with the left and right arrows.

**Comment by joshmiethe** [comment]
Added styles that are a bit more aesthetically pleasing. (a3a5fbb)
